Add support for VoiceChannel region overrides
DV8FromTheWorld/JDA pull request #1622
Opened 2021-05-17 12:37 UTC by Xirado

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This pull request adds support for VoiceChannel region overrides

2021-05-17 12:42 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
> +     * This will return {@link Region#UNKNOWN} if the region of this channel is set to Automatic.
I think it makes more sense to have a `Region#AUTOMATIC` to represent this.

2021-05-17 14:45 UTC, MinnDevelopment requested changes

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
>          return Region.fromKey(region);
```suggestion
        return region != null ? Region.fromKey(region) : Region.AUTOMATIC;
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
> +     * <br><b>This is only available to {@link net.dv8tion.jda.api.entities.VoiceChannel VoiceChannels!}</b></br>
```suggestion
     * <br><b>This is only available to {@link net.dv8tion.jda.api.entities.VoiceChannel VoiceChannels}!</b>
     *
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
> +        if(shouldUpdate(REGION))
```suggestion
        if (shouldUpdate(REGION))
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
> +        if((fields & REGION) == REGION)
```suggestion
        if ((fields & REGION) == REGION)
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
> +            throw new IllegalArgumentException("Region is not usable for VoiceChannel region overrides!");
```suggestion
        if (getType() != ChannelType.VOICE)
            throw new IllegalStateException("Can only change region on voice channels!");
        Checks.check(Region.VOICE_CHANNEL_REGIONS.contains(region), "Region is not usable for VoiceChannel region overrides!");
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
> +            this.region = region.getKey();
```suggestion
        this.region = region == Region.AUTOMATIC ? null : region.getKey();
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java
> +        return Region.fromKey(region);
```suggestion
        return region == null ? Region.AUTOMATIC : Region.fromKey(region);
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java
> +     * <br>The default value is {@link Region#AUTOMATIC}</br>
```suggestion
     * <br>The default value is {@link Region#AUTOMATIC}
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
> +    Region getRegion();
This is missing a `getRegionRaw()` similar to `Guild#getRegionRaw`.

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
> +     * This will return {@link Region#AUTOMATIC} if the region of this channel is set to Automatic.
```suggestion
     * <br>This will return {@link Region#AUTOMATIC} if the region of this channel is set to Automatic.
```

2021-05-17 14:45 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/Region.java
> +    public static final EnumSet<Region> VOICE_CHANNEL_REGIONS =
This needs documenation, what does this set represent? Also, the set is modifiable which is a problem.

2021-05-18 10:14 UTC, Xirado commented
@MinnDevelopment is there something you'd like me to change?

2021-06-06 20:31 UTC, MinnDevelopment commented
I think this PR is still missing an event and it should deprecate Guild#getRegion and related features.

2021-06-06 21:28 UTC, Xirado commented
@MinnDevelopment I have deprecated Guild#getRegion, Guild#getRegionRaw and GuildManager#setRegion
If you know, if there are more methods involving Guild regions, please let me know.

2021-06-06 21:34 UTC, MinnDevelopment commented
Here are some more:

- GuildAction#setRegion
- GuildUpdateRegionEvent (and the overload in ListenerAdapter)

Also, the deprecation should include a `@ReplaceWith` rather than a `@ForRemoval`.

2021-06-06 21:53 UTC, Xirado commented
> Here are some more:
> 
> * GuildAction#setRegion
> * GuildUpdateRegionEvent (and the overload in ListenerAdapter)
> 
> Also, the deprecation should include a `@ReplaceWith` rather than a `@ForRemoval`.

Alright those are now deprecated and i fixed the annotation.
I'll look out for more methods regarding guild regions

2021-06-07 00:03 UTC, MinnDevelopment requested changes
Please also add the `@DeprecatedSince("4.3.0")` annotation to all the deprecated features.

2021-06-07 00:03 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateRegionEvent.java
> +    public static final String IDENTIFIER = "rtc_region";
Just name this `"region"` we don't need to follow the stupid api names

2021-06-07 00:03 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateRegionEvent.java
> +     * @return The old raw region String
Document null case here

2021-06-07 00:03 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
> +     * @deprecated This event is no longer supported by discord
```suggestion
     * @deprecated This event is no longer supported by discord, use {@link #onVoiceChannelUpdateRegion(VoiceChannelUpdateRegionEvent)} instead.
```

2021-06-07 10:55 UTC, MinnDevelopment requested changes

2021-06-07 10:55 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateRegionEvent.java
> +     * This will return null if the Region of this {@link VoiceChannel VoiceChannel} is set to Automatic.
```suggestion
     * @return The old raw region String or null if the was Region is set to Automatic.
```

2021-06-07 10:55 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateRegionEvent.java
> +     * This will return null if the Region of this {@link VoiceChannel VoiceChannel} is set to Automatic.
```suggestion
     * @return The new raw region String or null if the Region is set to Automatic.
```

2021-06-07 11:06 UTC, merged