Add retrieveUser and retrieveMessage helper methods
DV8FromTheWorld/JDA pull request #1684
Opened 2021-06-20 20:14 UTC by arynxd

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This PR implements some helper retrieve methods for private reaction events.

2021-06-20 20:31 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/message/priv/react/GenericPrivateMessageReactionEvent.java
> +     * @since  4.3.0
4.3.0 is already released

2021-06-20 20:31 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/message/priv/react/GenericPrivateMessageReactionEvent.java
> +
Unnecessary empty line

2021-06-29 16:21 UTC, DV8FromTheWorld commented
@arynxd bump

2021-06-29 20:52 UTC, arynxd commented
Thanks for the bump :D

2021-06-29 20:55 UTC, MinnDevelopment requested changes
Would be nice to link to `retrieveUser` with an `@see` in `getUser` to improve discoverability.

2021-06-29 20:55 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/events/message/priv/react/GenericPrivateMessageReactionEvent.java
> +     * @since  4.3.0
```suggestion
     * @since  4.3.1
```

2021-07-31 19:26 UTC, arynxd commented
I broke my fork so will re-open this PR

2021-07-31 19:26 UTC, closed without merging