Fix outdated sticker field name
DV8FromTheWorld/JDA pull request #1732
Opened 2021-07-16 08:36 UTC by Andre601

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: #1731 

## Description

Updated `stickers` to `sticker_items` in the EntityBuilder

2021-07-16 10:02 UTC, MinnDevelopment commented
This needs to adjust the documentation on `Message#getStickers` to state that these stickers are partial, and limited to just the necessary information to render it. This means you only get the id, format type, and name.

----

Unrelated to this pull request:

I noticed that, when sending a message, you still receive the `stickers` array in addition to `sticker_items`. Although, this is deprecated so we can probably just ignore it.

Another thing, the guild object might also contain rich sticker objects, which we could potentially add support for if discord would document it. There also is a `GET/stickers/:sticker_id/guild` endpoint that seems to be undocumented as well.

2021-07-16 14:41 UTC, Andre601 commented
> This needs to adjust the documentation on `Message#getStickers` to state that these stickers are partial, and limited to just the necessary information to render it. This means you only get the id, format type, and name.

Adressed this.

2021-07-17 10:42 UTC, MinnDevelopment requested changes

2021-07-17 10:42 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     * <br>The MessageStickers returns may only contain necessary information such as id, format type and name.
```suggestion
     * <br>The returned MessageStickers may only contain necessary information such as the sticker id, format type, name, and icon url.
```

2021-07-17 10:49 UTC, merged