Update Permissions
DV8FromTheWorld/JDA pull request #1797
Opened 2021-08-31 13:35 UTC by DManstrator

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

## Description

Removed `Permission.MESSAGE_READ` and used the existing `Permission.VIEW_CHANNEL` instead. Also `Permission.USE_SLASH_COMMANDS` was renamed to `Permission.USE_APPLICATION_COMMANDS`.

Notes for users (can be copy pasted for Discord):
```
---
**`Permission.MESSAGE_READ` was removed** since it is the old version of **`Permission.VIEW_CHANNEL`, use that instead**.
**`Permission.USE_SLASH_COMMANDS`** was renamed to **`Permission.USE_APPLICATION_COMMANDS`**.
```

2021-08-31 13:40 UTC, DManstrator commented
@DV8FromTheWorld When looking at the permissions, I saw that `Read Text Channels & See Voice Channels` is called `View Channels` in the UI too (on Server, Channel and Category) and it belongs to the General Server Permissions. Should I change that too? I would also reorder the permissions to match the current UI.

2021-09-10 03:43 UTC, DV8FromTheWorld requested changes

2021-09-10 03:43 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
> +        checkPermission(Permission.VIEW_CHANNEL, "You cannot pin a message in a channel you can't access. (MESSAGE_READ)");
These error messages still reference `MESSAGE_READ`.
Please replace all references to `MESSAGE_READ` throughout the code.

2021-09-18 00:20 UTC, DManstrator commented
Waiting for #1827 before merging now.

2021-09-19 12:45 UTC, DManstrator commented
@DV8FromTheWorld I am done with that PR for now, let me know if you want something to be changed.

2021-09-19 19:08 UTC, DV8FromTheWorld approved these changes
This seems fine to me.

2021-09-19 19:08 UTC, merged