Updated magic numbers to use the Message#MAX_CONTENT_LENGTH constant
DV8FromTheWorld/JDA pull request #1870
Opened 2021-11-01 08:27 UTC by Tais993

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This PR replaces multiple magic numbers with the Message#MAX_CONTENT_LENGTH constant.
This makes updating JDA when the content length updates easier.
Just changing the constants value and the docs should be enough.

2021-11-01 08:32 UTC, Andre601 requested changes
The `check` method has a variant with `String.format` in it for easier formatting.

2021-11-01 08:32 UTC, Andre601 commented on src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
> +        Checks.check(text.length() <= Message.MAX_CONTENT_LENGTH, "Provided text for message must be less than " + Message.MAX_CONTENT_LENGTH + " characters in length");
```suggestion
        Checks.check(text.length() <= Message.MAX_CONTENT_LENGTH, "Provided text for message must be less than %d characters in length", Message.MAX_CONTENT_LENGTH);
```

2021-11-01 08:32 UTC, Andre601 commented on src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
> +        Checks.check(newContent.length() <= Message.MAX_CONTENT_LENGTH, "Provided newContent length must be " + Message.MAX_CONTENT_LENGTH + " or less characters.");
```suggestion
        Checks.check(newContent.length() <= Message.MAX_CONTENT_LENGTH, "Provided newContent length must be %d or less characters.", Message.MAX_CONTENT_LENGTH);
```

2021-11-06 12:28 UTC, MinnDevelopment approved these changes

2021-11-07 19:46 UTC, merged