add Interaction#getUserLocale and Interaction#getGuildLocale
DV8FromTheWorld/JDA pull request #1960
Opened 2021-12-21 15:29 UTC by caneleex

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

this PR adds `Interaction#getUserLocale` and `Interaction#getGuildLocale`. see https://github.com/discord/discord-api-docs/pull/4265. I'm not too sure about the behavior of `getGuildLocale` because there's a separate field for the preferred guild locale (however that is still only changeable with the `COMMUNITY` feature, effectively being `Guild#getLocale`), so feel free to comment on that.

2022-01-11 06:06 UTC, DV8FromTheWorld requested changes

2022-01-11 06:06 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
> +        this.guildLocale = guildLocale;
`guildLocale` is unneeded

2022-01-11 06:06 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
> +    }
This is implemented as a `default` method in the interface and is unneeded

2022-01-11 17:36 UTC, caneleex commented on src/main/java/net/dv8tion/jda/api/interactions/Interaction.java
> +     * @return The language of the invoking user or null if the type is {@link InteractionType#PING PING}
should I just make this Nonnull until receiving PING is added?

2022-01-11 17:41 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/interactions/Interaction.java
> +     * @return The language of the invoking user or null if the type is {@link InteractionType#PING PING}
PING is only for webhook interactions which we don't, currently don't plan to, support

2022-01-12 14:25 UTC, MinnDevelopment commented
Could you rebase and target this onto the `rework/interactions` branch instead?

2022-01-12 15:54 UTC, caneleex commented
I fucked up the rebase. I'll open a new pr.

2022-01-12 15:54 UTC, closed without merging