Dont override latest message id on deletion event
DV8FromTheWorld/JDA pull request #2013
Opened 2022-02-04 15:21 UTC by ishwi

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: #2009

## Description

The internal handle of the Message Deletion event no longer sets the LatestMessageIdLong to 0.

2022-02-04 22:09 UTC, DV8FromTheWorld approved these changes

2022-02-05 05:11 UTC, DV8FromTheWorld commented
Actually, I forgot: We need to update the docs for `getLatestMessageId` to no longer mention that the id gets reset if the message gets deleted.
We need to instead mention that the id could point to a deleted message if `MessageChannel#retrieveMessageById` is used

2022-02-05 13:04 UTC, MinnDevelopment requested changes
Please also update the relevant docs on the getters for latest message id

2022-02-06 01:22 UTC, ishwi reviewed
Is the text added clear or should it be expressed in any other way?

2022-02-11 16:56 UTC, MinnDevelopment commented
We need to make a decision on the TODO for line 100/101:

> //TODO-v5: Revisit this. Surely this should be Nullable instead of throw an exception...

@DV8FromTheWorld do you have any final thoughts on this? If we decide not to change the behavior, we should remove the comment in this PR.

2022-02-11 22:40 UTC, DV8FromTheWorld commented
Let's remove the exception from this getter. That means we no longer need the hasLastMessageId getter anymore either.

2022-02-19 13:05 UTC, MinnDevelopment commented
@ishwi can you remove the exception and `hasLatestMessage` getter? After that, it should be ready to merge.

2022-02-19 21:30 UTC, DV8FromTheWorld requested changes

2022-02-19 21:30 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
> +     * so calling {@link #retrieveMessageById(long)} with this id can throw {@link net.dv8tion.jda.api.requests.ErrorResponse#UNKNOWN_MESSAGE UNKNOWN_MESSAGE}</b></u>
```suggestion
     * so calling {@link #retrieveMessageById(long)} with this id can result in an {@link net.dv8tion.jda.api.requests.ErrorResponse#UNKNOWN_MESSAGE UNKNOWN_MESSAGE} error</b></u>
```

2022-02-19 21:30 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
> +     * so calling {@link #retrieveMessageById(long)} with this id can throw {@link net.dv8tion.jda.api.requests.ErrorResponse#UNKNOWN_MESSAGE UNKNOWN_MESSAGE}</b></u>
```suggestion
     * so calling {@link #retrieveMessageById(long)} with this id can result in an {@link net.dv8tion.jda.api.requests.ErrorResponse#UNKNOWN_MESSAGE UNKNOWN_MESSAGE} error</b></u>
```

2022-02-19 21:31 UTC, DV8FromTheWorld approved these changes

2022-02-19 21:32 UTC, merged