Message interface declutter: Message#getMentions()
DV8FromTheWorld/JDA pull request #2015
Opened 2022-02-05 07:52 UTC by DV8FromTheWorld

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

## Description
This PR helps declutter the `Message` interface by moving all of the `getMentionedX` methods to their own construct: `MessageMentions`

## Migration Reference
| Old  | New |
| ------------- | ------------- |
| `Message#mentionsEveryone()`  | `MessageMentions#mentionsEveryone()` |
| `Message#getMentionedUsers()`  | `MessageMentions#getUsers()`  |
| `Message#getMentionedUsersBag()  | `MessageMentions#getUsersBag()`  |
| `Message#getMentionedChannels()`  | `MessageMentions#getChannels()`  |
| `Message#getMentionedChannelsBag()`  | `MessageMentions#getChannelsBag()`  |
| `Message#getMentionedRoles()`  | `MessageMentions#getRoles()`  |
| `Message#getMentionedRolesBag()`  | `MessageMentions#getRolesBag()`  |
| `Message#getMentionedMembers()`  | `MessageMentions#getMembers()`  |
| `Message#getMentionedMembers(Guild)`  | `MessageMentions#getMembers(Guild)`  |
| `Message#getMentions(MentionType...)`  | `MessageMentions#getMentions(MentionType...)`  |
| `Message#isMentioned(IMentionable, MentionType...)`  | `MessageMentions#isMentioned(IMentionable, MentionType...)`  |

#### New:
 - `MessageMentions#getEmotes()`
 - `MessageMentions#getEmotesBag()`
   - Technically both of these already existed on `Message` (and still do even in this PR). They were added to `MessageMentions` for completion and simplicity for discoverability and implementation.

This PR supersedes #1835

2022-02-05 08:03 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/internal/entities/MessageMentionsImpl.java
> +//TODO-v5 | Docs
```suggestion
```

2022-02-05 08:06 UTC, DV8FromTheWorld commented
Either in this PR or in a follow up one we need to add support for the methods sought after by https://github.com/DV8FromTheWorld/JDA/pull/1605

Additionally, we need to make `getChannels` return `List<Channel>`, not `List<TextChannel>`

2022-02-05 13:03 UTC, MinnDevelopment commented
This could probably also be used for `OptionMapping#getMentions`

2022-02-05 17:40 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/MessageMentions.java
> +     * Indicates if this Message mentions everyone using @everyone or @here.
```suggestion
     * Indicates if this Message mentions everyone using {@literal @everyone or @here}.
```

2022-02-05 17:40 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/MessageMentions.java
> +     * <br>It will provide the {@link Message()#getGuild() Message's Guild} to {@link #getMembers(Guild)}.
```suggestion
     * <br>It will provide the {@link Message#getGuild() Message's Guild} to {@link #getMembers(Guild)}.
```

2022-02-05 17:40 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/MessageMentions.java
> +     *         If this is a system message
Maybe we should just throw on `Message#getMentions`?

2022-02-20 16:31 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/api/entities/MessageMentions.java
> +     * @since  3.4.0
Copy paste. Need to remove all of these annotations.

2022-02-20 22:57 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/MessageMentions.java
> +    List<TextChannel> getChannels();
Shouldn't this be `List<GuildChannel>`?

2022-04-27 19:58 UTC, DV8FromTheWorld commented
I've reviewed everything added by @MinnDevelopment and ✅ 
I can't approve my own PR heh.

Changes for `getChannels(Class<T>)` to come.

2022-04-27 19:59 UTC, DV8FromTheWorld commented
@MinnDevelopment this is ready for any other signoff you'd like to do.

2022-04-27 20:13 UTC, DV8FromTheWorld commented
I wonder if we should change the bag getter implementations to instead rely on the list getters to take advantage of caching.

2022-04-27 21:16 UTC, MinnDevelopment requested changes

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/Mentions.java
> +    <T extends GuildChannel> List<T> getChannels(Class<T> clazz);
```suggestion
    <T extends GuildChannel> List<T> getChannels(@Nonnull Class<T> clazz);
```

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/Mentions.java
> +     * <p><b>This may include GuildChannels from other {@link net.dv8tion.jda.api.entities.Guild Guilds}</b>
Maybe add an example

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/Mentions.java
> +    <T extends GuildChannel> Bag<T> getChannelsBag(Class<T> clazz);
```suggestion
    <T extends GuildChannel> Bag<T> getChannelsBag(@Nonnull Class<T> clazz);
```

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
> +    public <T extends GuildChannel> List<T> getChannels(Class<T> clazz)
```suggestion
    public <T extends GuildChannel> List<T> getChannels(@Nonnull Class<T> clazz)
```

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
> +    public <T extends GuildChannel> Bag<T> getChannelsBag(Class<T> clazz)
```suggestion
    public <T extends GuildChannel> Bag<T> getChannelsBag(@Nonnull Class<T> clazz)
```

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
> +            return clazz.isInstance(channel) ? (T) channel : null;
```suggestion
            return clazz.isInstance(channel) ? clazz.cast(channel) : null;
```

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
> +    @SuppressWarnings("unchecked")
```suggestion
```

2022-04-27 21:16 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
> +          GuildChannel channel = this.matchChannel(matcher);
```suggestion
        Function<Matcher, T> matchTypedChannel = matcher -> {
            GuildChannel channel = this.matchChannel(matcher);
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *             <li>{@link Permission#MESSAGE_HISTORY Permission.MESSAGE_HISTORY}</li>
```suggestion
     *             <li>{@link Permission#MESSAGE_ADD_REACTION}</li>
     *             <li>{@link Permission#MESSAGE_HISTORY}</li>
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         or {@link Permission#MESSAGE_HISTORY Permission.MESSAGE_HISTORY}
```suggestion
     *     <br>The reaction request was attempted after the account lost {@link Permission#MESSAGE_ADD_REACTION}
     *         or {@link Permission#MESSAGE_HISTORY}
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>Also can happen if the account lost the {@link Permission#MESSAGE_HISTORY Permission.MESSAGE_HISTORY}</li>
```suggestion
     *         due to {@link Permission#VIEW_CHANNEL} being revoked
     *     <br>Also can happen if the account lost the {@link Permission#MESSAGE_HISTORY}</li>
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *             <li>Missing {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE}.
```suggestion
     *             <li>Missing {@link Permission#MESSAGE_MANAGE}.
```

2022-04-28 15:00 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *             <li>Missing {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL}.
```suggestion
     *             <li>Missing {@link Permission#VIEW_CHANNEL}.
```

2022-04-28 15:01 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The unpin request was attempted after the account lost {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE} in
```suggestion
     *     <br>The unpin request was attempted after the account lost {@link Permission#MESSAGE_MANAGE} in
```

2022-04-28 15:01 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         due to {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL} being revoked, or the
```suggestion
     *         due to {@link Permission#VIEW_CHANNEL} being revoked, or the
```

2022-04-28 15:01 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *             <li>Missing {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL}.
```suggestion
     *             <li>Missing {@link Permission#VIEW_CHANNEL}.
```

2022-04-28 15:01 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *             <li>Missing {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE}.
```suggestion
     *             <li>Missing {@link Permission#MESSAGE_MANAGE}.
```

2022-04-28 15:01 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         due to {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL} being revoked, or the
```suggestion
     *         due to {@link Permission#VIEW_CHANNEL} being revoked, or the
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The pin request was attempted after the account lost {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE} in
```suggestion
     *     <br>The pin request was attempted after the account lost {@link Permission#MESSAGE_MANAGE} in
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *              {@link GuildChannel GuildChannel}.</li>
```suggestion
     *              {@link GuildChannel}.</li>
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         does not have {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE} in
```suggestion
     *         {@link GuildChannel}, and the currently logged in account
     *         does not have {@link Permission#MESSAGE_MANAGE} in
```

2022-04-28 15:02 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The delete was attempted after the account lost {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE} in
```suggestion
     *     <br>The delete was attempted after the account lost {@link Permission#MESSAGE_MANAGE} in
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         due to {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL} being revoked, or the
```suggestion
     *         due to {@link Permission#VIEW_CHANNEL} being revoked, or the
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     * {@link Permission#MESSAGE_MANAGE Permission.MESSAGE_MANAGE} in the channel.
```suggestion
     * {@link Permission#MESSAGE_MANAGE} in the channel.
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:03 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:04 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:04 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:04 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:04 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         not have {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND}
```suggestion
     *         not have {@link Permission#MESSAGE_SEND}
```

2022-04-28 15:04 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:05 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:05 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND} in
```suggestion
     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND} in
```

2022-04-28 15:05 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:05 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         typically due to being kicked or removed, or after {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL}
```suggestion
     *         typically due to being kicked or removed, or after {@link Permission#VIEW_CHANNEL}
```

2022-04-28 15:05 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:05 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         typically due to being kicked or removed, or after {@link Permission#VIEW_CHANNEL Permission.VIEW_CHANNEL}
```suggestion
     *         typically due to being kicked or removed, or after {@link Permission#VIEW_CHANNEL}
```

2022-04-28 15:06 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:06 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND} in
```suggestion
     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND} in
```

2022-04-28 15:06 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:06 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND} in
```suggestion
     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND} in
```

2022-04-28 15:06 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a system message, or data message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a system message, or data message (output of {@link MessageBuilder})
```

2022-04-28 15:06 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND Permission.MESSAGE_SEND} in
```suggestion
     *     <br>The edit was attempted after the account lost {@link Permission#MESSAGE_SEND} in
```

2022-04-28 15:07 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:07 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:07 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:08 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:08 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:08 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:08 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     *         If this is a Data Message (output of {@link MessageBuilder MessageBuilder})
```suggestion
     *         If this is a Data Message (output of {@link MessageBuilder})
```

2022-04-28 15:37 UTC, DV8FromTheWorld commented on src/main/java/net/dv8tion/jda/api/entities/Mentions.java
> +     * <p><b>This may include GuildChannels from other {@link net.dv8tion.jda.api.entities.Guild Guilds}</b>
Done 👍

2022-04-29 09:47 UTC, MinnDevelopment approved these changes

2022-05-06 07:23 UTC, merged