Return MessageReaction for getReactionX methods
DV8FromTheWorld/JDA pull request #2026
Opened 2022-02-10 16:22 UTC by duncte123

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

Closes Issue: https://github.com/DV8FromTheWorld/JDA/projects/5#card-76582150

## Description

Makes `Message#getReactionX` return `MessageReaction` instead of `MessageReaction.ReactionEmote`

2022-02-11 01:55 UTC, java-coding-prodigy commented
#2015 seems to cover this issue.

2022-02-11 06:10 UTC, duncte123 commented
> #2015 seems to cover this issue.

That one only touches the mentions, this is specifically for emotes

2022-02-11 06:11 UTC, java-coding-prodigy commented
> That one only touches the mentions, this is specifically for emotes

Oh I see.

2022-02-11 12:50 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
> +    public MessageReaction getReactionById(@Nonnull String id)
I saw you already mentioned this on discord, can you make this a default in the interface?

2022-02-11 16:53 UTC, MinnDevelopment approved these changes

2022-02-15 09:16 UTC, Tais993 requested changes
According to the [structure-guide ](https://github.com/DV8FromTheWorld/JDA/wiki/6%29-JDA-Structure-Guide) they should be aligned.

_I do acknowledge that this doesn't happen everywhere though, there's a lot of inconsistencies with the indentation of javadoc_

2022-02-15 09:16 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     * @see net.dv8tion.jda.api.entities.MessageReaction
```suggestion
     * @see    #getReactionById(String)
     * @see    #getReactionByUnicode(String)
     * @see    net.dv8tion.jda.api.entities.MessageReaction
```

2022-02-15 09:16 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     * @see net.dv8tion.jda.api.entities.MessageReaction
```suggestion
     * @see    #getReactionById(long)
     * @see    #getReactionByUnicode(String)
     * @see    net.dv8tion.jda.api.entities.MessageReaction
```

2022-02-15 09:16 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     * @see net.dv8tion.jda.api.entities.MessageReaction
```suggestion
     * @see    #getReactionById(long)
     * @see    net.dv8tion.jda.api.entities.MessageReaction
```

2022-02-15 09:16 UTC, Tais993 commented on src/main/java/net/dv8tion/jda/api/entities/Message.java
> +     * @see net.dv8tion.jda.api.entities.MessageReaction
```suggestion
     * @see    net.dv8tion.jda.api.entities.MessageReaction
```

2022-02-27 14:32 UTC, Sanduhr32 approved these changes

2022-04-18 16:44 UTC, DV8FromTheWorld approved these changes

2022-04-18 16:44 UTC, merged