Add guild welcome screens
DV8FromTheWorld/JDA pull request #2264
Opened 2022-09-27 17:54 UTC by freya022

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [X] Library interface (affecting end-user code) 
- [X] Documentation
- [ ] Other: \_____ 

Closes Issue: #1987 

## Description
This PR adds support for guild welcome screens.

- [ ] Support editing
- [ ] Docs
- [ ] Test editing
- [ ] Test getting welcome screen
- [ ] Test getting channel emojis

2022-10-18 21:00 UTC, MinnDevelopment requested changes

2022-10-19 15:16 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
> +        public Channel(Guild guild, long id, String description, EmojiUnion emoji)
The constructor is used by the entity builder

2022-10-19 15:21 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
> +        private final String description;
Client doesn't let me save when it's empty / blank

2022-10-19 15:24 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
> +    default GuildWelcomeScreenManager clearDescription()
Just a shortcut to avoid using null

2022-10-19 16:17 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
> +        public Channel(Guild guild, long id, String description, EmojiUnion emoji)
Then there are 2 choices:

- Make it an interface with an impl class
- Move checks into the constructor

However, as it stands right now, people will simply use the constructor before finding the factory methods.

2022-10-19 16:18 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
> +        private final String description;
Then we should check for this too

2022-10-19 16:18 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
> +    default GuildWelcomeScreenManager clearDescription()
Then I think it can be removed

2022-10-19 19:10 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
> +        public Channel(Guild guild, long id, String description, EmojiUnion emoji)
Moved GuildWelcomeScreen and Channel into impl classes

2022-10-19 20:47 UTC, MinnDevelopment reviewed
Almost done i think

2022-10-19 20:47 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
> + *        .clearDescription()
```suggestion
 *        .setDescription("Welcome to our guild")
```

2022-10-19 20:47 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/managers/GuildWelcomeScreenManager.java
> +    GuildWelcomeScreenManager setWelcomeChannels(@Nonnull Collection<GuildWelcomeScreen.Channel> channels);
```suggestion
    GuildWelcomeScreenManager setWelcomeChannels(@Nonnull Collection<? extends GuildWelcomeScreen.Channel> channels);
```

2022-10-19 20:47 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/Invite.java
> +         * <br>This will be {@code null} if the Guild has no welcome screen.
Its also null if its created from a `Guild` instance it seems

2022-10-19 20:47 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/GuildWelcomeScreen.java
> +public interface GuildWelcomeScreen
Can you add a getManager() to this too?

2022-10-20 17:42 UTC, MinnDevelopment approved these changes

2022-12-06 15:12 UTC, merged